import type { MachineConfig, MachineKey } from "./types";

export const machineDataList: Record<MachineKey, MachineConfig> = {
    "farm1": {
        "name": "Small Coffee Farm",
        "type": "farm",
        "icon": "/assets/coffeeQ/beanFarm1.png",
        "cost": 100,
        "levelRequired": 0,
        "productionTime": 10000,
        "uses": null,
        "produces": "rawCoffeeBeans",
        "baseBatchSize": 1,
    },
    "farm2": {
        "name": "Coffee Farm",
        "type": "farm",
        "icon": "/assets/coffeeQ/beanFarm2.png",
        "cost": 1000000,
        "levelRequired": 0,
        "productionTime": 40000,
        "uses": null,
        "produces": "rawCoffeeBeans",
        "baseBatchSize": 5,
    },
    "coffeeBeanRoaster1": {
        "name": "Old Roaster",
        "type": "roaster",
        "icon": "/assets/coffeeQ/roaster1.png",
        "cost": 200,
        "levelRequired": 0,
        "productionTime": 5000,
        "uses": "rawCoffeeBeans",
        "produces": "roastedCoffeeBeans",
        "baseBatchSize": 1,
    },
    "coffeeBeanRoaster2": {
        "name": "Modern Roaster",
        "type": "roaster",
        "icon": "/assets/coffeeQ/roaster2.png",
        "cost": 100000,
        "levelRequired": 14,
        "productionTime": 20000,
        "uses": "rawCoffeeBeans",
        "produces": "roastedCoffeeBeans",
        "baseBatchSize": 5,
    },
    "coffeeGrinder1": {
        "name": "Used Coffee Grinder",
        "type": "grinder",
        "icon": "/assets/coffeeQ/coffeeGrinder1.png",
        "cost": 1000,
        "levelRequired": 2,
        "productionTime": 20000,
        "uses": "roastedCoffeeBeans",
        "produces": "groundCoffee",
        "baseBatchSize": 1,
    },
    "coffeeGrinder2": {
        "name": "Coffee Grinder",
        "type": "grinder",
        "icon": "/assets/coffeeQ/coffeeGrinder2.png",
        "cost": 500000,
        "levelRequired": 18,
        "productionTime": 30000,
        "uses": "roastedCoffeeBeans",
        "produces": "groundCoffee",
        "baseBatchSize": 3,
    },
    "coffeeBrewer1": {
        "name": "Coffee Brewer",
        "type": "brewer",
        "icon": "/assets/coffeeQ/coffeeBrewer1.png",
        "cost": 3000,
        "levelRequired": 4,
        "productionTime": 60000,
        "uses": "groundCoffee",
        "produces": "brewedCoffee",
        "baseBatchSize": 2,
    },
    "espressoMachine1": {
        "name": "Small Espresso Machine",
        "type": "brewer",
        "icon": "/assets/coffeeQ/espressoMachine1.png",
        "cost": 10000,
        "levelRequired": 6,
        "productionTime": 20000,
        "uses": "groundCoffee",
        "produces": "espresso",
        "baseBatchSize": 1,
    },
    "milkSteamer": {
        "name": "Milk Steamer",
        "type": "brewerAssistant",
        "icon": "/assets/coffeeQ/milkSteamer.png",
        "cost": 20000,
        "levelRequired": 10,
        "productionTime": 12000,
        "uses": "espresso",
        "produces": "latte",
        "baseBatchSize": 1,
    },
    "espressoMachine2": {
        "name": "Espresso Machine",
        "type": "brewer",
        "icon": "/assets/coffeeQ/espressoMachine2.png",
        "cost": 10000000,
        "levelRequired": 25,
        "productionTime": 20000,
        "uses": "groundCoffee",
        "produces": "espresso",
        "baseBatchSize": 2,
    },
    "frenchPress1": {
        "name": "French Press",
        "type": "brewer",
        "icon": "/assets/coffeeQ/frenchPress1.png",
        "cost": 400,
        "levelRequired": 12,
        "productionTime": 60000,
        "uses": "groundCoffee",
        "produces": "brewedCoffee",
        "baseBatchSize": 1,
    },
    "pourOver1": {
        "name": "Manual Pour-Over",
        "type": "brewer",
        "icon": "/assets/coffeeQ/pourOver1.png",
        "cost": 1000,
        "levelRequired": 14,
        "productionTime": 30000,
        "uses": "groundCoffee",
        "produces": "brewedCoffee",
        "baseBatchSize": 1,
    },
};
